### ISSUE TITLE
Support for Canvas

### ISSUE THREAD

**Issue by ArturRod** [PantelisGeorgiadis/dcmjs-ecg#1]
Hello, I am interested in the project, there are things that are very good and I have liked them a lot, I have also developed an ECG view but in canvas, could this project also be drawn instead of SVG in Canvas?

I am grateful to have more people who develop this type of project.

**Comment by PantelisGeorgiadis** [comment]
Hello @ArturRod! Thank you for your kind comment! Good to see that we are sharing common interests! After a quick search, I discovered that once you have the SVG XML, you can actually render it in an HTML5 canvas object (https://stackoverflow.com/questions/3768565/drawing-an-svg-file-on-a-html5-canvas). I deliberately avoided pairing the output to an HTML element type (e.g. canvas, webgl, etc) because I wanted this library to able to be used in both browser and node.js.

**Comment by PantelisGeorgiadis** [comment]
@ArturRod, I checked your ecg-dicom-web-viewer project. Great stuff! Do you happen to have any 8-bit sample DICOM ECG dataset or any SOP class other than the 12-lead one?

**Comment by ArturRod** [comment]
Hi @PantelisGeorgiadis 
Currently I have not worked with 8-bit, all the dicoms that have happened to me or that I have for tests are 12-lead.

**Comment by PantelisGeorgiadis** [comment]
@ArturRod, if you agree, should we close this issue?

**Comment by ArturRod** [comment]
@PantelisGeorgiadis Yes, i close the issue.
